{
 "title": "Netdata: RabbitMQ Overview",
 "description": "Detailed stats for RabbitMQ (queries, cache, locks, etc)",
 "tags": [
  "RabbitMQ",
  "software"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,1m,5m,1h,6h,1d" },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(up{env=~\".+\"},env)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(netdata_rabbitmq_memory{env=\"$env\",instance=~\".+\"},instance)"
   },
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(netdata_rabbitmq_memory{env=\"$env\",instance=~\"$host\"},source)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queued Messages",
   "type": "graph",
   "description": "Number of messages in the queue",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(netdata_rabbitmq_queued_messages{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Message Rates",
   "type": "graph",
   "description": "Count of messages delivered, published, redelivered and delivered in acknowledgement mode",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "messages/s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(irate(netdata_rabbitmq_message_rates_total{env=\"$env\",instance=~\"$host\",source=~\"$source\"}[10m])) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Global Counts",
   "type": "graph",
   "description": "Global metrics counts",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": " counts" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(netdata_rabbitmq_global_counts{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": " Total memory used by RabbitMQ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "Memory used" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_rabbitmq_memory{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "description": "Free space left on hard disk",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_rabbitmq_disk_space{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Erlang Processes",
   "type": "graph",
   "description": "Total RabbitMQ processes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_rabbitmq_processes{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "Number of file descriptors used",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "descriptors" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(netdata_rabbitmq_file_descriptors{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Socket Descriptors",
   "type": "graph",
   "description": "File descriptors used as sockets",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "descriptors" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_rabbitmq_sockets{env=\"$env\",instance=~\"$host\",source=~\"$source\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  }
 ]
}